version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: barberia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hola123**
      MYSQL_DATABASE: barberia
    ports:
      - "3307:3306" # Cambiado a 3307 para evitar conflicto
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: barberia-php
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
volumes:
  db_data:
